### ISSUE TITLE
BMO crashes if photutils is not setup

### ISSUE THREAD

**Issue by albireox** [sdss/bmo#7]
```python
[WARNING]: BMOMissingImportWarning: photutils is missing. Background subtraction will not work.
Traceback (most recent call last):
  File "/home/sdss4/software/git//bmo/0.2.6/bin/bmo_main.py", line 20, in <module>
    from bmo.bmo_main import BMOActor
  File "/home/sdss4/software/git/bmo/0.2.6/python/bmo/bmo_main.py", line 25, in <module>
    from bmo.devices.manta import MantaCameraSet
  File "/home/sdss4/software/git/bmo/0.2.6/python/bmo/devices/manta.py", line 80, in <module>
    class MantaExposure(object):
  File "/home/sdss4/software/git/bmo/0.2.6/python/bmo/devices/manta.py", line 138, in MantaExposure
    def subtract_background(self, background=None, sigma_clip=sigma_clip,
NameError: name 'sigma_clip' is not defined
```

**Comment by albireox** [comment]
BMO is no more.
